// The free library (the Articles tab, /articles): free articles now, videos to follow. Add one here and it appears on
// /articles with its own page at /articles/<slug>, ending with "Return to free resources" and a link to its product.
// Copy is carried over word for word from Remi's documents. In body text and references, **text** is bold, *text* is
// italic and [label](href) is a link (see components/articles/Inline.tsx). A body entry is a paragraph, { h2 } a question heading,
// or { figure } an image. A video is optional: `video: { provider: 'vimeo' | 'youtube', id: '…', title: '…' }` shows it above the text.
import type { VideoRef } from '@/components/shared/VideoEmbed';
import { RABBIT_HOLES, type Topic } from '@/content/perspectives';

export type ArticleBlock = string | { h2: string } | { figure: { src: string; alt: string; width: number; height: number } };

export type Article = {
  slug: string; title: string; date: string;        // date as 'YYYY-MM-DD'
  summary: string;                                  // the standfirst under the title, and the line on the library card
  image?: string;                                   // the library card's illustration
  topic: Topic;                                     // the cluster it sits in on /articles (one of ARTICLE_CLUSTERS)
  product?: string;                                 // slug in content/products.ts: the product the article leads on to
  body: ArticleBlock[]; references?: string[];
  video?: VideoRef;
};

/** Where an article sends readers back to. */
export const LIBRARY_HREF = '/articles';

/** The library's topic clusters are the Perspectives page's four rabbit holes (RABBIT_HOLES in content/perspectives.ts):
 *  each shows its articles, then opens the matching conversations (the videos) in the Perspectives archive. */
export const ARTICLE_CLUSTERS = RABBIT_HOLES.map(h => ({
  ...h, id: h.topic.toLowerCase().replace(/[^a-z]+/g, '-').replace(/^-|-$/g, ''),
  videosHref: `/perspectives?topic=${encodeURIComponent(h.topic)}#archive`,
}));
export const clusterOf = (topic: Topic) => ARTICLE_CLUSTERS.find(c => c.topic === topic);

export const ARTICLES: Article[] = [
  {
    slug: "why-insight-isnt-enough", topic: 'Human change',
    title: "Why Do I Keep Repeating the Same Patterns Even When I Understand Myself?",
    summary: "Why insight isn’t enough, and what inner work makes possible.",
    date: '2026-09-30', image: "/assets/rabbit-holes/kb-read-insight.webp", product: "why-do-i-keep-doing-this",
    body: [
      "You can know exactly why you people-please and still say yes when everything in you wants to say no. You can recognise your fear of abandonment while watching yourself chase someone who keeps withdrawing. You can explain the family dynamics that taught you to become responsible for everyone and still find yourself carrying the emotional weight of a room before anyone has asked you to.",
      "This is one of the most frustrating experiences in personal development. We have the insight. Sometimes we can see the pattern while we are doing it, which adds a particularly unpleasant layer of self-criticism … surely, if I know this much about myself, I should be able to do something different?",
      "I have spent more than twenty years working with that gap. Understanding can be enormously helpful, but there comes a point when another explanation leaves us standing in much the same place. We need to become curious about what becomes possible when we bring our attention to the inner experience we have been explaining.",
      { figure: { src: "/assets/articles/why-insight-isnt-enough.webp", width: 1379, height: 920,
        alt: "Why Insight Isn’t Enough. Understanding the pattern, then doing the inner work: “I know why I people-please.” becomes “I practise saying no and staying with the guilt.” “I know I’m afraid of rejection.” becomes “I meet that fear with compassion.” “I know I need support.” becomes “I allow myself to ask and receive.” “I know why I over-function.” becomes “I let others carry their responsibilities.” Insight recognises the pattern. Inner work develops the capacity to respond differently." } },
      { h2: "Why doesn’t self-awareness always lead to change?" },
      "Knowing that you learned to keep the peace tells you something about your history. It does not necessarily make conflict feel manageable today. You might understand that another person’s disappointment is theirs to experience, yet feel such intense guilt when it appears that you immediately surrender your boundary.",
      "The understanding and the emotional capacity are different achievements. One allows you to recognise what is happening. The other develops as you become able to remain with feelings that previously required you to appease, withdraw, defend yourself or take control.",
      "Courses can help us do this work. So can good books and thoughtful conversations. But we can also complete an extraordinary amount of learning without changing how we treat ourselves when we are frightened, ashamed or hurt. Our vocabulary develops while our inner world remains organised around the same old protections.",
      { h2: "Can seeking insight become a form of avoidance?" },
      "Sometimes the search for understanding becomes a comfortable place to stay. We analyse our attachment style, investigate another framework and discover a more sophisticated explanation for our behaviour. Meanwhile, the grief we have never allowed ourselves to feel remains untouched.",
      "I see intellectualising as a protective strategy when thinking about an experience keeps us at a distance from experiencing it. Someone can speak brilliantly about loneliness while barely allowing themselves to acknowledge how lonely they feel. They can describe their childhood with remarkable clarity and hurry past the sadness of what they needed and did not receive.",
      "There is intelligence in that protection. At some point, understanding may have been safer than feeling. Inner work begins by respecting that history and becoming curious about whether we can now approach what has been kept at a distance, with enough support and gentleness for something different to happen.",
      { h2: "What does doing the inner work actually mean?" },
      "My Self-Esteem Triad brings this work into focus through our relationship with emotions, emotional needs and boundaries. At its centre are the experiences of being worthy, lovable and enough. Each side asks us to consider how those experiences are expressed in the way we live.",
      "Our relationship with emotions includes whether we can acknowledge hurt without calling ourselves weak, experience anger without immediately condemning it, or allow grief without imposing a deadline. Emotional integration involves becoming increasingly capable of being with what we feel, at a pace we can manage, while retaining a relationship with ourselves.",
      "Research by Ford and colleagues (2018) found that habitually accepting thoughts and emotions without judging them was associated with better psychological health. Across laboratory, diary and longitudinal studies, acceptance was also linked with lower negative emotional responses to stress. The finding concerned accepting internal experiences; it did not require accepting the situations causing them.",
      "Our emotional needs deserve that same attention. We may know we need connection, consideration or support and still behave as though asking would be unreasonable. The work includes discovering what happens inside us when our needs become visible. Do we feel embarrassed? Burdensome? Afraid that needing something will cost us the relationship?",
      { h2: "Why are boundaries difficult even when we know what to say?" },
      "Many people know the boundary they need. They have rehearsed the words. What they struggle with is the feeling that arrives after they say them.",
      "Someone becomes disappointed, and guilt appears. Someone challenges the boundary, and self-doubt takes over. We begin explaining, softening and negotiating until the boundary has quietly disappeared. Afterwards, we search for a better script, although the words may have been perfectly adequate.",
      "Within the Triad, boundaries connect directly with emotions and emotional needs. Holding a boundary may require us to acknowledge our need for rest while allowing the discomfort of someone wishing we were available. We learn to consider that discomfort without automatically treating it as evidence that we have done something wrong.",
      { h2: "How does over-functioning keep us disconnected from ourselves?" },
      "Over-functioning can be difficult to recognise because it is so often rewarded. We are capable, reliable and excellent in a crisis. People appreciate how much we carry, and we may have built a considerable part of our identity around being the person who copes.",
      "Yet sometimes all that doing protects us from an uncomfortable inner experience. Being indispensable may feel safer than wondering whether we would still matter if we stopped helping. Managing someone else’s distress may spare us the helplessness of allowing them to struggle. Their needs become urgent while ours remain indefinitely postponable.",
      "Fritz and Helgeson (1998) studied “unmitigated communion”, a focus on others to the exclusion of oneself. Across four studies, they distinguished this pattern from a caring orientation towards others and linked it with psychological distress, reliance on others for self-esteem and self-neglect. Their work gives us a useful way to examine the cost of caring when we repeatedly disappear from the equation.",
      { h2: "Can self-improvement reinforce the feeling that I’m not enough?" },
      "I love learning. I also think we need to examine the promise we attach to it. If every course carries the hope that the next version of us will finally deserve acceptance, learning can become a way of repeatedly postponing our own worthiness.",
      "Compassion offers another starting point. Breines and Chen (2012) found across four experiments that responding to mistakes or weaknesses with self-compassion increased several forms of motivation to improve, including effort after failure and motivation to make amends. We can take responsibility and develop without making contempt for ourselves the engine of change.",
      "What becomes available through inner work is often very ordinary. We ask for support and allow ourselves to receive it. We acknowledge hurt without immediately explaining it away. We let someone be disappointed while remaining thoughtful about our boundary. We begin experiencing ourselves as someone whose feelings and needs belong in the conversation.",
      "The pattern may still appear. This time, perhaps, we can stay with ourselves long enough to make a different choice.",
    ],
    references: [
      "Breines, J.G. and Chen, S. (2012) ‘Self-compassion increases self-improvement motivation’, *Personality and Social Psychology Bulletin*, 38(9), pp. 1133–1143. doi: 10.1177/0146167212445599. [Read the free full text](https://self-compassion.org/wp-content/uploads/publications/selfimp.motivation.pdf).",
      "Ford, B.Q., Lam, P., John, O.P. and Mauss, I.B. (2018) ‘The psychological health benefits of accepting negative emotions and thoughts: Laboratory, diary, and longitudinal evidence’, *Journal of Personality and Social Psychology*, 115(6), pp. 1075–1092. doi: 10.1037/pspp0000157. [Read the free full text](https://pmc.ncbi.nlm.nih.gov/articles/PMC5767148/).",
      "Fritz, H.L. and Helgeson, V.S. (1998) ‘Distinctions of unmitigated communion from communion: Self-neglect and overinvolvement with others’, *Journal of Personality and Social Psychology*, 75(1), pp. 121–140. doi: 10.1037/0022-3514.75.1.121. [Read the free abstract](https://pubmed.ncbi.nlm.nih.gov/9686454/).",
    ],
  },
  {
    slug: "the-moment-you-leave-yourself", topic: 'Relationships',
    title: "Why Do I Lose Myself in Relationships?",
    summary: "The moment you leave yourself, and how compassionate inner work helps you return.",
    date: '2026-09-30', image: "/assets/rabbit-holes/kb-read-leave.webp", product: "love-without-losing-yourself",
    body: [
      "Someone says something that hurts you, and before you have had time to acknowledge the hurt, you are explaining why they probably didn’t mean it. You are tired, but they need something, so you agree. You want to raise a concern, then notice their mood and decide that now is probably not the time. Somehow, it rarely becomes the time.",
      "These moments can seem too ordinary to deserve attention. We call them being considerate, keeping the peace or choosing our battles. Sometimes that is exactly what they are. But when we repeatedly move away from our own feelings and needs to preserve a relationship, something happens inside us. We remain available to the other person while becoming increasingly unavailable to ourselves.",
      "I think this is where self-abandonment deserves our attention. We often notice it afterwards, when we feel resentful, exhausted or strangely absent from our own life. The more useful place to become curious is the moment our experience stopped counting.",
      { figure: { src: "/assets/articles/the-moment-you-leave-yourself.webp", width: 1379, height: 920,
        alt: "The Moment You Leave Yourself. Leaving myself, then staying with myself: I feel hurt: “It’s probably nothing.” or “My feelings matter.” I need support: “I shouldn’t burden anyone.” or “I can ask for help.” I want to say no: “I’ll say yes to keep the peace.” or “I can honour my limit.” Someone is disappointed: “I have to fix how they feel.” or “I can care and hold my boundary.”" } },
      { h2: "What does self-abandonment look like?" },
      "Self-abandonment can happen while we appear remarkably functional. We organise everything, respond thoughtfully and make life easier for the people around us. Meanwhile, our own discomfort is being edited out of the conversation.",
      "Perhaps we tell ourselves we are too sensitive. Perhaps we decide that needing reassurance would be embarrassing, or that asking for support would add to someone else’s burden. We might even recognise what we need and immediately explain why we should manage without it. Knowing ourselves does not prevent us from dismissing ourselves.",
      "Compromise leaves room for both people to matter. When self-abandonment becomes familiar, our own experience can start to feel like an inconvenience we must resolve before we are allowed to participate.",
      { h2: "Why do I put other people’s feelings before my own?" },
      "For some of us, paying close attention to other people became an early route to connection or safety. We learned when to be quiet, when to help and which feelings were unlikely to be welcomed. Being easy to love may have seemed to require becoming very undemanding.",
      "Internal Family Systems offers a compassionate way to explore these patterns. Within the IFS model, parts that please, control, withdraw or take excessive responsibility can be understood as protectors. Their strategies may be costly, but their intention is to prevent something the person experiences as threatening. The model emphasises respecting those protectors and developing a relationship with them before approaching the vulnerability they guard (IFS Institute, n.d.).",
      "This changes the quality of our attention. We can become curious about what the accommodating part fears would happen if we spoke honestly. Would someone leave? Become angry? Decide we were selfish? A part of us may still experience those possibilities as far more dangerous than the gradual loss of ourselves.",
      { h2: "How can compassionate self-inquiry help?" },
      "Compassionate self-inquiry begins with a willingness to notice what is actually happening. We might recognise tightness, hurt, numbness or an immediate urge to reassure the other person. We do not have to produce a sophisticated explanation before our experience deserves attention.",
      "Useful questions include, *What happened inside me just then? What am I trying to prevent? What do I need that I have already begun dismissing?* We can also notice how we feel towards the part that stepped in. Are we curious about it, or furious that it has done this again?",
      "That distinction matters. Inquiry can become another form of self-surveillance if we use it to catch ourselves being wrong. The possibility of change opens when we can listen without immediately requiring the answer to justify our feelings or make them disappear.",
      { h2: "What if I cannot feel compassion for myself?" },
      "Being told to offer ourselves compassion can feel surprisingly difficult. Someone may understand the idea and still feel irritated by their vulnerability, ashamed of their needs or frightened of what might emerge if they stopped controlling everything.",
      "Gilbert and Procter’s (2006) work on compassionate mind training specifically addressed people with high shame and self-criticism who found self-warmth difficult or frightening. Their small, uncontrolled pilot reported improvements in self-criticism, shame and self-soothing. It also recognised that compassion may need to become an accessible experience, rather than another instruction someone is expected to follow.",
      "I developed Emotion Integration Technique for people whose protection makes that access difficult. The starting point may be frustration, blankness, dissociation or simply not knowing. In EIT, we work outward through the layers of protection until genuine compassion becomes available, then bring that compassion inward towards the original experience. We approach what is underneath at a pace the person can manage (Pearson, 2026).",
      "This is facilitated work. Its purpose is to respect the protection while helping someone develop a different relationship with the feelings they have needed to keep at a distance.",
      { h2: "How do I stay connected to myself when someone is disappointed?" },
      "My Self-Esteem Triad connects our relationship with emotions, emotional needs and boundaries, with *worthy, lovable, enough* at the centre. It gives us a practical way to consider what returning to ourselves might involve.",
      "We acknowledge the emotion we have pushed aside. We allow the need we have discounted to matter. Then we consider what boundary or response would honour that experience. Perhaps we need time before answering, want to express hurt or need to revisit a commitment we made too quickly.",
      "The difficult part may be allowing the other person to have feelings about our response. We can care about their disappointment while continuing to assess what is right for us. Guilt may appear, and we can listen to it without automatically assuming it proves we have done something wrong.",
      "Self-compassion is something we can develop through practice. Neff and Germer’s (2013) randomised trial found that participants in a Mindful Self-Compassion programme reported greater increases in self-compassion and wellbeing than a waitlist group. This supports practising a more supportive inner relationship, including during the ordinary moments when our old responses appear.",
      { h2: "What does returning to myself look like?" },
      "Returning may begin after we have already agreed, minimised the hurt or taken responsibility for something that belongs to someone else. We can notice what happened and reconsider our response. We can acknowledge the part that tried to protect the relationship while making room for the experience it pushed aside.",
      "The relationship itself also deserves an honest assessment. Some people can make room for our needs; others repeatedly punish their expression. Inner work should help us recognise those conditions and decide how to respond, including when distance or leaving becomes necessary.",
      "We may still feel uncertain. The other person may still be disappointed. But we begin to have a place in the conversation, and the relationship no longer gets our participation at the automatic expense of our own experience.",
    ],
    references: [
      "Gilbert, P. and Procter, S. (2006) ‘Compassionate mind training for people with high shame and self-criticism: Overview and pilot study of a group therapy approach’, *Clinical Psychology & Psychotherapy*, 13(6), pp. 353–379. doi: 10.1002/cpp.507. [Available as free full text](https://self-compassion.org/wp-content/uploads/publications/Gilbert.Procter.pdf).",
      "IFS Institute (n.d.) ‘The Internal Family Systems model outline’. Available at: [IFS Institute](https://ifs-institute.com/resources/articles/internal-family-systems-model-outline) (Accessed: 30 September 2026).",
      "Neff, K.D. and Germer, C.K. (2013) ‘A pilot study and randomized controlled trial of the Mindful Self-Compassion program’, *Journal of Clinical Psychology*, 69(1), pp. 28–44. doi: 10.1002/jclp.21923. [Available as free full text](https://self-compassion.org/wp-content/uploads/publications/Neff-Germer-MSC-RCT-2012.pdf).",
      "Pearson, R. (2026) ‘Emotion Integration Technique’. *Remi Pearson*. Available at: [Remi Pearson](/ideas-models/emotion-integration-technique)",
    ],
  },
  {
    slug: "why-relationships-trigger-me", topic: 'Relationships',
    title: "Why Do Relationships Trigger Me So Much?",
    summary: "Why loving someone brings old patterns to the surface, and how we begin responding differently.",
    date: '2026-09-30', image: "/assets/rabbit-holes/ls-hero.webp", product: "five-paths-to-a-healthy-relationship",
    body: [
      "You can be perfectly capable in the rest of your life and find yourself almost unrecognisable when someone you love pulls away. You check your phone, rehearse what to say and wonder whether you have asked for too much. Or you experience the opposite. Someone wants to talk about feelings, and suddenly you cannot find any of yours. You become practical, defensive or unavailable, even though the relationship matters to you.",
      "Relationships have an extraordinary talent for finding the places where our emotional capacity is still developing. We may have understood a pattern years ago, yet closeness brings us into contact with the feelings underneath it. Knowing we fear rejection does not necessarily make rejection easier to experience. Knowing we disappear to keep the peace does not automatically help us remain present when someone is disappointed.",
      { figure: { src: "/assets/articles/why-relationships-trigger-me.webp", width: 1024, height: 1536,
        alt: "Why Do Relationships Trigger Me So Much? When protection takes over, and when I can stay with myself. They seem distant: “I chase for reassurance.” or “I notice my fear and ask what’s happening.” We disagree: “I say I’m fine to keep the peace.” or “I acknowledge my hurt and express what I need.” The conversation gets emotional: “I shut down or take over.” or “I pause and return when I can be present.” They are disappointed with me: “I abandon my boundary to make it better.” or “I can care about their feelings and hold my limit.” I need support: “I stay quiet and hope they notice.” or “I name what I need and ask directly.” They need space: “I assume I’m being rejected.” or “I notice what I’m assuming and ask for clarity.” Something has hurt me: “I criticise them or turn against myself.” or “I acknowledge the hurt and talk about what happened.” We have had an argument: “I rush to fix everything or avoid them.” or “I allow time to settle, then invite repair.” Catch the pattern. Meet it with compassion. Practise a different response." } },
      { h2: "Why does closeness bring out my protective patterns?" },
      "When someone matters to us, their availability carries weight. We have something we want to protect, something we could lose, and needs that may feel uncomfortable to acknowledge. A change in their tone can become a question about our worth. A disagreement can begin to feel like the end of the relationship.",
      "Attachment research helps explain these responses. Simpson and Rholes (2017) describe how attachment anxiety and avoidance shape reactions to stressful situations in romantic relationships. Some people intensify their efforts to obtain reassurance; others distance themselves or suppress their need for support. Our expectations of ourselves and other people influence what we notice, what we fear and how we respond.",
      "Those responses can have a history, but the present deserves attention too. A partner who is inconsistent, contemptuous or unwilling to repair creates real difficulties. Understanding our attachment patterns should help us assess a relationship more accurately, including whether it offers enough care and reciprocity.",
      { h2: "How do we get caught in the same relationship cycle?" },
      "Something happens. We give it meaning, often very quickly. Protection begins, the other person reacts, and the cycle gathers momentum. One person pursues harder while the other retreats further. Someone becomes silent, so their partner presses for an answer. Both may want connection while responding in ways that make it harder to find.",
      "Within Internal Family Systems, these responses can be explored as protective parts. A part may please, withdraw or control because it fears what would happen without that strategy. IFS emphasises developing a respectful relationship with protectors and listening to their concerns, rather than trying to eliminate them (IFS Institute, n.d.).",
      "This gives us somewhere useful to begin. What am I afraid will happen if I stop carrying the whole relationship? What feeling becomes available when I stop explaining everything away? We can explore these questions while keeping responsibility accurately placed. Recognising our response does not make us responsible for another person’s conduct.",
      { h2: "How can I stay connected to myself when I’m triggered?" },
      "I call the moment we begin moving away from ourselves our Point of Departure. We may feel it as tightness, urgency, blankness or an immediate need to fix something. Catching that moment gives us an opportunity to notice what is happening before the familiar response makes every decision.",
      "My Emotion Integration Technique works with the protection that can make emotional contact difficult. When compassion is unavailable, we begin with what is accessible, including frustration, numbness or not knowing. Through facilitated work, we move outward until genuine compassion becomes available, then bring it inward towards the experience being protected (Pearson, 2026).",
      "That work develops capacity. We become more able to acknowledge hurt, express a need or hold a boundary while discomfort is present. We can listen without immediately rescuing, and ask what someone means before responding to what we fear they mean. These abilities develop through experience, support and practice.",
      { h2: "Where can I begin creating a healthier relationship?" },
      "The Five Paths to a Healthy Relationship brings this work into a practical starting point. It explores staying connected to yourself, recognising the attachment cycle, communicating needs and boundaries, repairing after rupture, and creating emotional safety together.",
      "Perhaps you already recognise where you disappear, chase or take too much responsibility. The next step is learning how to meet those moments with more honesty and capacity. The Five Paths gives you short lessons and a workbook to begin applying the ideas to your own relationship patterns, in your own time.",
      "**[Explore The Five Paths to a Healthy Relationship](/products/five-paths-to-a-healthy-relationship) … AUD $29.**",
    ],
    references: [
      "IFS Institute (n.d.) ‘The Internal Family Systems model outline’. Available at: [IFS Institute](https://ifs-institute.com/resources/articles/internal-family-systems-model-outline) (Accessed: 30 September 2026).",
      "Pearson, R. (2026) ‘Emotion Integration Technique’. *Remi Pearson*. Available at: [Remi Pearson](/ideas-models/emotion-integration-technique)",
      "Simpson, J.A. and Rholes, W.S. (2017) ‘Adult attachment, stress, and romantic relationships’, *Current Opinion in Psychology*, 13, pp. 19–24. doi: 10.1016/j.copsyc.2016.04.006. [Read the free full text](https://socialinteractionlab.psych.umn.edu/sites/socialinteractionlab.psych.umn.edu/files/files/simpson_rholes_cop_2017.pdf).",
    ],
  },
  {
    slug: "why-do-i-keep-repeating-the-same-patterns", topic: 'Human change',
    title: "Why Do I Keep Repeating the Same Patterns?",
    summary: "Tell me the truth … what am I missing?",
    date: '2026-09-30', image: "/assets/rabbit-holes/tt-hero.webp", product: "find-the-gap-in-your-own-life",
    body: [
      "You find yourself having the same conversation with a different person. Or taking responsibility for something you promised yourself you would stop carrying. Perhaps you set a goal, genuinely care about it, and then watch another month disappear into everybody else’s priorities. The circumstances change enough to feel new, but somewhere along the way you recognise the ending.",
      "It can be frustrating, particularly when you’ve already done considerable work on yourself. You can explain the pattern, identify where it began and talk thoughtfully about why it happens. Yet when the moment arrives, you still say yes, take over, go quiet or postpone the decision. Eventually, “Why do I keep doing this?” becomes a more searching question … “What am I not seeing?”",
      { figure: { src: "/assets/articles/why-do-i-keep-repeating-the-same-patterns.webp", width: 935, height: 1402,
        alt: "Why Do I Keep Repeating the Same Patterns? Find the gap with the Critical Alignment Model. Start with outcome & purpose: What do I want instead, and why does it matter? The repeating pattern: I take responsibility for everything, then feel overwhelmed and resentful. What keeps happening, and where to look. Above the line, intended & available. Environment: I expect shared responsibility, but haven’t made the expectations clear. What values, expectations and ground rules have I explicitly established? Structure: I want help, but ownership, resources and agreements are vague. Who owns what? What resources, sequence and benchmarks support the outcome? Below the line, expressed. Implementation: We agree on a plan, then I step in and take the work back. What actually happens? Where does the process or follow-through depart from the agreement? People: I struggle to hold my limit, or someone lacks the skills to carry their role. What skills, role clarity and accountability need attention? Address the gap you find: Clarify expectations. Build support. Examine follow-through. Develop capacity. Use it in relationships, leadership, business or your own life." } },
      { h2: "Why do the same problems keep happening?" },
      "There are several places to look, and we tend to return to whichever explanation is most familiar. If we’re accustomed to examining our childhood, we look there. If we’re action-oriented, we make another plan. If we’re used to carrying responsibility, we decide we need to try harder. Each approach may reveal something useful, while leaving other parts of the situation almost untouched.",
      "This is where I use the Critical Alignment Model, or CAM. We begin with the outcome and purpose, then examine four dimensions: Environment, Structure, Implementation and People. The model gives us a way to investigate the distance between what we intend and what is actually happening, and identify what needs attention (Pearson, 2026a).",
      "Let’s take a familiar pattern: **I keep taking responsibility for everything, then feeling overwhelmed and resentful.** It might appear in a relationship, where you organise everything and initiate every difficult conversation. At work, you become the person everyone relies on to solve the problem. In your personal life, the things you want to pursue keep being pushed aside because someone else needs you.",
      "There may be genuine demands and people who aren’t carrying their share. Those belong in the analysis. So does the possibility that some of your own arrangements and responses keep making this outcome more likely.",
      { h2: "How do I identify what is keeping me stuck?" },
      "First, name the outcome you actually want. “I want to stop feeling overwhelmed” tells us what you want relief from, but leaves the alternative fairly vague. Perhaps you want a relationship with shared responsibility, a team that can make decisions without you, or time you can reliably devote to your own goals. What would that look like in an ordinary week?",
      "Then we examine the four dimensions.",
      "**Environment** concerns the values, expectations and ground rules you have explicitly established. If shared responsibility matters, have you named what that means? Have you communicated your limits, or are you hoping someone will notice how much you’re carrying? An expectation that exists only in your head gives other people very little to work with.",
      "**Structure** examines what you have organised to support the outcome: resources, responsibilities, sequence and benchmarks. Who owns what? What time is available? How will you know whether things are improving? You can sincerely value your own development while leaving no room for it in your calendar.",
      "**Implementation** brings us to what happens in practice. You agreed to delegate, then took the work back. You planned to protect an evening, then made yourself available. You intended to speak honestly, then said, “It’s fine.” Here we examine the process, follow-through and repeated departures from what was intended.",
      "**People** concerns the skills, roles and accountability needed, including your own capacity. Can you make a clear request, hold a boundary or give feedback? Can the other person fulfil the responsibility they’ve accepted? We need to distinguish between something that hasn’t been clarified, something that hasn’t been learned and something someone repeatedly chooses not to do.",
      "Above the line, Environment and Structure establish what is intended and available. Below the line, Implementation and People show how it is expressed. Examining both helps us locate the gap more precisely (Pearson, 2026a).",
      { h2: "Why do I keep doing something I want to change?" },
      "Sometimes the practical gap is straightforward. Sometimes you discover that you’ve organised your life carefully, yet abandon the arrangement when someone is disappointed or uncomfortable.",
      "That deserves attention. Being needed might give you a sense of belonging. Taking over might spare you the uncertainty of trusting someone else. Remaining endlessly available might protect you from the fear that a boundary will change the relationship. These are possibilities to explore, rather than conclusions to impose.",
      "In my Safe versus Risky Problems work, we examine whether the problem we keep discussing allows us to postpone a more difficult truth. “Nobody helps me” may be accurate. There may also be an uncomfortable question about what happens when help is offered, or what you’re willing to do when a clear request is repeatedly ignored (Pearson, 2026b).",
      "As I put it: “More information does not close a gap you are still organised around protecting” (Pearson, 2026a).",
      { h2: "How can I be honest with myself without blaming myself?" },
      "An honest analysis requires enough compassion to keep looking. Otherwise, noticing your contribution becomes another opportunity to call yourself weak, foolish or somehow defective, and the examination quickly loses its usefulness.",
      "Research supports taking a kinder approach to our mistakes. Across four experiments, Breines and Chen found that self-compassion could increase motivation to improve, including motivation to make amends and effort following a test failure (Breines and Chen, 2012). We can acknowledge something difficult about our behaviour while remaining interested in how it developed and what would help us respond differently.",
      "Values Alignment adds another question: what do my choices currently make room for? If you say your own life matters, but repeatedly surrender every available hour, there is a discrepancy worth examining. Your constraints matter, and change may take time. Even so, the discrepancy gives you somewhere concrete to begin (Pearson, 2026c).",
      { h2: "How do I stop repeating the same patterns?" },
      "Choose a change that addresses the gap you actually found. An unclear agreement needs clarification. A missing skill needs development. A boundary you repeatedly abandon may require inner work around the feelings that arise when you honour it.",
      "Then observe what happens. A meta-analysis of 138 experimental studies found that interventions encouraging people to monitor their progress improved goal attainment on average, with larger effects when progress was recorded or reported (Harkin *et al.*, 2016). Keep a simple record of the agreement, what happened and what you learned, so you have evidence to work with next time.",
      "If you want help examining your own situation, **[Find the Gap in Your Own Life](/products/find-the-gap-in-your-own-life)**, **AUD $29**, is the place to begin. It uses Critical Alignment to help you identify what is preventing movement. Bring a real situation: the conversation you keep postponing, the responsibility you keep taking back, the goal that never gets room.",
      "For a broader exploration, **[Find the Truth of the Situation](/products/find-the-truth-of-the-situation)** brings together four programs for **AUD $79**: Find the Gap in Your Own Life; When Your Values and Your Life Stop Matching; Safe or Risky Problems?; and Let Truth Lead.",
      "Start with the pattern you’re tired of explaining. What does a careful look at it reveal that your familiar explanation has been leaving out?",
    ],
    references: [
      "Breines, J.G. and Chen, S. (2012) ‘Self-compassion increases self-improvement motivation’, *Personality and Social Psychology Bulletin*, 38(9), pp. 1133–1143. doi: 10.1177/0146167212445599. [Accessible full text](https://self-compassion.org/wp-content/uploads/publications/selfimp.motivation.pdf).",
      "Harkin, B., Webb, T.L., Chang, B.P.I., Prestwich, A., Conner, M., Kellar, I., Benn, Y. and Sheeran, P. (2016) ‘Does monitoring goal progress promote goal attainment? A meta-analysis of the experimental evidence’, *Psychological Bulletin*, 142(2), pp. 198–229. doi: 10.1037/bul0000025. [Repository record and full-text access](https://eprints.whiterose.ac.uk/id/eprint/91437/).",
      "Pearson, R. (2026a) ‘Critical Alignment Model’, *Remi Pearson*. Available at: [Remi Pearson](/ideas-models/critical-alignment-model)",
      "Pearson, R. (2026b) ‘Safe versus Risky Problems’, *Remi Pearson*. Available at: [Remi Pearson](/ideas-models/safe-problems-risky-truths)",
      "Pearson, R. (2026c) ‘Values Alignment Technique’, *Remi Pearson*. Available at: [Remi Pearson](/ideas-models/values-alignment-technique)",
    ],
  },
  {
    slug: "how-do-i-stop-micromanaging-my-team", topic: 'Founders & business',
    title: "How Do I Stop Micromanaging My Team?",
    summary: "How to lead without carrying everybody, using the Critical Alignment Model.",
    date: '2026-09-30', image: "/assets/rabbit-holes/ld-hero.webp", product: "critical-alignment-model-for-leaders",
    body: [
      "You delegate something, explain what needs to happen and get back to your own work. Then come the questions. You answer them, clarify a few things, check progress and discover something has been missed. Eventually you take it back because doing it yourself feels quicker than having another conversation about it. By Friday, you’re exhausted and wondering why nobody seems capable of making a decision without you.",
      "It’s tempting to conclude that you need better people. Sometimes there genuinely is a capability issue. But before you make that judgement, there’s a question worth sitting with … have you created the conditions in which someone can succeed without constantly returning to you?",
      { figure: { src: "/assets/articles/how-do-i-stop-micromanaging-my-team.webp", width: 1024, height: 1536,
        alt: "Before You Take the Work Back… Find the gap through the five dimensions of CAM. 1. Purpose: Do they understand the outcome and why it matters? Example: Help the customer find the right support. Above the line, intended & available. 2. Environment: Have we written down the values, standards and expectations? Example: Raise concerns early and speak honestly. 3. Structure: Are the resources, decision authority and benchmarks clear? Example: Agree the budget, timeline and quality standard. Below the line, expressed. 4. Implementation: What actually happens when the work is carried out? Example: Check whether the agreed process is used and delays are communicated. 5. People: What skills, role clarity or accountability need developing? Example: Coach their judgement before taking over. Address the gap you find. Critical Alignment Model, Remi Pearson." } },
      { h2: "Why does my team rely on me for everything?" },
      "A team can become dependent on its leader through ordinary, repeated interactions. Someone brings a problem and you solve it. They make a decision and you change it, without explaining the thinking behind the change. They wait for approval because the last time they acted independently, they discovered a standard nobody had mentioned.",
      "You may be working incredibly hard while remaining the person who holds the context, remembers the priorities and decides whether something is good enough. Your team has tasks. You still have most of the thinking.",
      "The Critical Alignment Model helps us examine this through five dimensions: **Purpose, Environment, Structure, Implementation and People**. We establish what matters and what supports it, then examine what happens in practice and what capacity needs developing (Pearson, 2026).",
      "One principle I teach is, “People come last, because People come first.” If we haven’t attended to the preceding dimensions, we can end up judging people for struggling within arrangements that were never clear enough to support them.",
      { h2: "How do I give my team clear direction?" },
      "**Purpose comes first.** What are we trying to achieve, and why does it matter? Someone who understands the purpose can begin evaluating options. Someone who has only been given a task will often need another instruction when circumstances change.",
      "“Respond to customer enquiries” leaves plenty unresolved. Are we trying to help people make an informed decision, resolve a concern or find the right support? What would a successful interaction look like? Those distinctions shape the response.",
      "Purpose also helps us assess priorities. Everything can look urgent when nobody understands what matters most. A leader needs to make that thinking available, so the team can increasingly use it themselves.",
      { h2: "How do I build a culture of ownership?" },
      "**Environment concerns the vision, values, standards and expectations we explicitly establish.** If we want initiative, what does that mean here? Which decisions can someone make? What should they raise early? How do we expect people to handle disagreement or acknowledge a mistake?",
      "Then we examine whether those written ground rules match the unwritten ones. You might say, “We welcome ideas,” while becoming defensive whenever someone questions your approach. You might ask for ownership while rewarding the person who checks every detail with you.",
      "Amy Edmondson’s study of 51 work teams found that psychological safety was associated with team learning behaviours, including discussing errors, seeking feedback and asking for help (Edmondson, 1999). A team needs room to reveal what it doesn’t understand if we expect it to learn.",
      "If this discrepancy feels familiar, **[The Ground Rules No One Wrote Down](/products/the-ground-rules-nobody-wrote-down)**, is a relevant place to explore it. Pay attention to what a new team member would learn by watching what gets accepted around here.",
      { h2: "How do I delegate without losing control?" },
      "**Structure gives people something reliable to work within.** It includes the resources, systems, sequence and benchmarks that support the outcome. Before handing something over, establish what success looks like, who owns it, what authority they have and where it connects with other people’s work.",
      "Imagine asking someone to organise an event. They need access to the budget, the delivery standards, the timeline and the decisions they can make. If that information stays in your head, questions are inevitable.",
      "Benchmarking matters here. “Do a great job” offers very little guidance. A benchmark makes the standard observable: enquiries answered within an agreed timeframe, information checked before publication, or the room ready before participants arrive. The benchmark should serve the purpose, rather than become another number we collect because we can.",
      "**[Benchmarking… What Good Actually Looks Like](/products/benchmarking-what-good-actually-looks-like)** focuses on this part of the work. Clear standards give both of you a basis for assessing progress beyond your personal impression of how things are going.",
      "Research also supports looking beyond individual attitude. Seibert, Wang and Courtright’s meta-analysis found that leadership, support and work characteristics were associated with psychological empowerment, while team empowerment was positively related to team performance (Seibert, Wang and Courtright, 2011).",
      { h2: "How do I hold people accountable without micromanaging?" },
      "**Implementation examines what actually happens.** Are the agreed systems used? Are priorities translated into scheduled work? Do people communicate delays while there is still time to respond, or wait until the deadline has passed?",
      "In my CAM Top Five system, weekly priorities connect with longer-term goals, and progress is made visible through an agreed review rhythm. Regular responsibilities also need their own schedule. Otherwise, the leader becomes the reminder system for things everyone already knows must happen (Pearson, 2026).",
      "That rhythm gives you somewhere to assess progress without constantly interrupting. It also helps you distinguish between someone who needs support and an agreement that isn’t being honoured. Both require attention, but they lead to different conversations.",
      { h2: "What if my team genuinely needs more development?" },
      "**People brings us to skills, roles and accountability.** Having clarified the preceding dimensions, we can assess capability more fairly. Can the person do what the role requires? Can they explain their decisions, recognise a problem and ask for appropriate support?",
      "Feedback should help develop their thinking. Ask what they noticed, which options they considered and what they would do differently. If you only provide the answer, they may complete today’s task while remaining just as dependent tomorrow.",
      "Your own capacity belongs in this examination too. Can you tolerate someone doing things differently when the agreed outcome is still achieved? Can you stay with the discomfort of a learning curve without immediately taking over? Being needed can feel reassuring, even while you’re complaining about how much everyone needs you.",
      { h2: "Where do I begin changing this?" },
      "Choose one responsibility that repeatedly returns to you and examine it through all five dimensions. Clarify its purpose, establish the expectations and support, observe what happens, then address the capability or accountability gap you actually find.",
      "**[Critical Alignment Model for Leaders](/products/critical-alignment-model-for-leaders)** is the next step if you want to apply this thinking to your own team. Bring the recurring problem you’re tired of solving. Look carefully at what you have established, what remains dependent on you and what needs to develop.",
      "The aim is a team that can increasingly understand, decide and follow through, with you available for the leadership the situation genuinely requires.",
    ],
    references: [
      "Edmondson, A. (1999) ‘Psychological safety and learning behavior in work teams’, *Administrative Science Quarterly*, 44(2), pp. 350–383. doi: 10.2307/2666999. [Accessible full text](https://web.mit.edu/curhan/www/docs/Articles/15341_Readings/Organizational_Learning_and_Change/Edmondson_1999_Psychological_safety.pdf).",
      "Pearson, R. (2026) ‘Critical Alignment Model for Leaders’, *Remi Pearson*. Drawing on the author’s training materials on Critical Alignment, written and unwritten ground rules, benchmarking and the CAM Top Five system. Available at: [Critical Alignment Model](/ideas-models/critical-alignment-model) and [Critical Alignment Model for Leaders](/products/critical-alignment-model-for-leaders).",
      "Seibert, S.E., Wang, G. and Courtright, S.H. (2011) ‘Antecedents and consequences of psychological and team empowerment in organizations: A meta-analytic review’, *Journal of Applied Psychology*, 96(5), pp. 981–1003. doi: 10.1037/a0022676. [Accessible abstract and publication details](https://www.researchwithrutgers.org/en/publications/antecedents-and-consequences-of-psychological-and-team-empowermen/).",
    ],
  },
  {
    slug: "build-a-business-that-runs-without-you", topic: 'Founders & business',
    title: "How Do You Build a Business That Can Run Without You?",
    summary: "How I went from coaching clients to building The Coaching Institute, and what replacing myself actually involved.",
    date: '2026-09-30', image: "/assets/rabbit-holes/bd-hero.webp", product: "from-practice-to-enterprise",
    body: [
      "I became a coach because I wanted to help myself. At the time, I was considering hiring a coach, and somewhere in that decision I became curious about learning the work myself. I wanted access to the materials behind the scenes. If something could help me change, I wanted to understand why it worked, how it worked and what else might become possible.",
      "I had spent much of my life being pretty miserable. I didn’t really know how to be happy, and I wanted to explore what it would take to become my favourite self. How do we lead an extraordinary life? What helps someone move beyond the ways they’ve learned to survive and begin living in a way they actually enjoy? Those questions fascinated me. They still do.",
      "That was the beginning of a business that eventually became far bigger than anything I had imagined. There was no grand plan for a coaching school when I started in 2003. There was me, learning about human behaviour, trying to change my own life and figuring out how to find clients.",
      { figure: { src: "/assets/articles/build-a-business-that-runs-without-you.webp", width: 1024, height: 1536,
        alt: "How Do You Build a Business That Can Run Without You? Make the work teachable. Help others carry it. When everything depends on me, and when the business can carry it: “I deliver every class and client experience” becomes “The work is recorded, documented and taught.” “I explain the same process again and again” becomes “The team can find the manual and checklist.” “I hold the standards in my head” becomes “Values and benchmarks make the standards clear.” “I take the work back when something is missed” becomes “Feedback and mentoring develop capability.” “I am needed at every level of delivery” becomes “Others lead the core work before taking on more.” The sequence I used: record the work, create facilitator notes, develop someone to deliver it, observe and give feedback, replace yourself in the core, move to the next level. Document the operations. Develop the people. Keep the values alive." } },
      { h2: "How did I grow my coaching business?" },
      "In the beginning, I spent a lot of time trying to get clients. I was doing the networking, having the conversations and looking for opportunities, but my attention was on whether someone would become a client. That made every interaction carry a little more weight than it needed to.",
      "Gradually, I stumbled into a different way of approaching it. When I gave the best of what I had in a conversation, a workshop or a networking event, people responded. I could help someone think differently, understand something they’d been struggling with or see a possibility they hadn’t considered. The conversation itself could be useful, whether or not anything happened afterwards.",
      "That became my approach to business. Give people something worthwhile. Find out about them. If there was a genuine match between what they wanted and what I could offer, we could work together.",
      "In my first year, I did around $25,000. In my second, around a quarter of a million dollars. By my third year, I was doing over a million (the business went on to do as much as $14,000,000 a year very shortly after that). I had established The Coaching Institute by 2004, and other coaches began asking how I was doing it.",
      "Sometimes, when I tried to explain, we seemed to be having different conversations. They wanted to know how to get the client. I was talking about how to be useful to the person in front of you, and how to recognise whether working together made sense.",
      "Along the way, I developed coaching systems I could use repeatedly with clients. I was learning what worked, how to deliver it and how to do it again. That gave me something I could teach, and the school began to grow.",
      { h2: "Why does a growing business become dependent on its founder?" },
      "At first, I did everything. Every event, every webinar, every mentoring session for every student. I knew the work, cared about the student experience and could deliver it, so I kept delivering it.",
      "That is a very understandable place to begin. You’re the person with the skill. You’ve created the opportunity. People are coming because they trust you, and you want to honour that trust. But as demand grows, the arrangement begins to show its limits. Every new opportunity requires more of your time, and the business keeps returning to you for the things it needs to function.",
      "In my **[From Practice to Enterprise](/products/from-practice-to-enterprise)** program, I explore this shift: developing the business means learning to build the systems and leadership through which other people can contribute, rather than remaining responsible for doing everything yourself.",
      "For me, that meant asking a question about work I already knew how to do. How could someone else learn to deliver it well?",
      { h2: "How do you replace yourself without losing quality?" },
      "I began documenting my work. I would record a webinar, have it transcribed and turn the transcription into facilitator notes. This was before the automated tools we now take for granted, so there was quite a bit of work involved in getting from a recording to something another person could actually use.",
      "Then someone else would run the class using those notes. I would listen to their delivery and give feedback. We could examine what they understood, what they had missed, where the notes needed improving and what needed more practice.",
      "A recording captured what I said. Developing a facilitator required helping them understand what they were doing and why. That distinction mattered. I wanted someone who could work with the material and the students, rather than simply read my words aloud.",
      "We repeated the process. The notes became more useful, the facilitator developed, and the work gradually became something that could be delivered well without me being the person delivering it.",
      { h2: "What should you delegate first?" },
      "I started with the core programs, the smallest programs, and worked through every aspect of their delivery. A webinar was one part. Mentoring, assessments and the other elements of the student experience also needed attention.",
      "Once I had replaced myself throughout the core program, I moved to the next level. Then the next. Eventually, that process extended through to our premium programs at $25,000.",
      "There was a sequence to it. We developed capability around the established work before moving further into the more advanced work. Each stage gave us a stronger foundation for what followed.",
      "Replacing yourself can sound like a single decision, as though one day you hire someone and hand over your role. My experience was much more granular. It happened through particular classes, particular responsibilities and particular systems, with feedback and development along the way.",
      { h2: "How do you turn what you know into business systems?" },
      "While that was happening in the student experience, I was also building the systems behind the scenes. As sales progressed and the business moved forward, I reverse engineered what had happened and backfilled the work that supported it.",
      "My rule was simple: if something happened more than once, it needed an operations manual.",
      "We documented the process, the checklist, the recurring activities and the things someone needed to know to carry out the work. The team could go into our shared drive, click a hyperlink and find the relevant material. They could access the operations manual, the to-do list or the daily responsibilities without needing me to reconstruct it for them.",
      "That made knowledge accessible beyond the person who happened to hold it. It also gave us something we could examine and improve. When a process depended on memory, much of it remained invisible until someone forgot a step or wasn’t available.",
      "This connects with Tom McKaskill’s work on preparing businesses for exit. In *Ultimate Exits*, he identifies undocumented knowledge and dependence on a small number of individuals as limitations, and examines how knowledge, people and resources need to support the transfer and expansion of a business’s capabilities (McKaskill, 2010).",
      "Even when selling is years away, it is useful to ask whether the knowledge that makes the business work can travel beyond you.",
      { h2: "How do you build a team you can trust?" },
      "Documentation was only part of what I built. Very early on, I also developed a team performance system, including a **[90-day cultural review](/products/the-90-day-review)**. We had a strong vision, mission and values, and those needed to be present in the ordinary working day.",
      "Feedback came through the filter of living the values and the vision. We had something explicit to refer to, rather than relying on whatever a leader happened to prefer that afternoon. We trained people in the vision and values, discussed them and used them to examine how we worked together.",
      "Someone joining the team went through a 90-day onboarding process and a mentorship program. By the end of that period, we could assess whether they were a cultural match as well as whether they could do the work.",
      "That distinction became important as the business grew. A capable person still needed to contribute to the kind of organisation we were building. Their effect on other people, their willingness to learn and how they approached responsibility mattered alongside their technical ability.",
      "My manual, included in **[the program](/products/from-practice-to-enterprise)** here, brings these elements together because systems, culture and leadership continually affect one another. A documented process needs people who can use it, improve it and take responsibility for its purpose (Pearson, 2011).",
      { h2: "What does it take to build beyond the founder?" },
      "Looking back, I can see how much of the work involved making things available to others that had previously lived inside me. The coaching became teachable. The delivery became documented. The standards became explicit. People had a way to learn, receive feedback and develop.",
      "I still had work to do as the founder. What changed was the work the business needed from me.",
      "I hadn’t started with ambitions to build The Coaching Institute. I began with a personal question about how to live differently, and followed it into conversations, coaching and eventually a school. As it grew, I kept learning how to make the work repeatable and how to help other people carry it.",
      "If your business currently depends on you for almost everything, start with one piece of work you do regularly. Record it. Explain your thinking. Help someone learn it, observe what happens and improve what supports them. That gives you somewhere practical to begin.",
      { h2: "Explore the work" },
      "**[From Practice to Enterprise](/products/from-practice-to-enterprise)** is the starting point for exploring the move beyond a business organised around your own delivery.",
      "**[Trust That Holds](/products/trust-that-holds)** draws on the TRUSTME model for the trust dimension of that work.",
      "For the broader collection, **[Build Beyond the Founder](/products/build-beyond-the-founder)** brings together From Practice to Enterprise, Core Improve Innovate and Trust That Holds.",
    ],
    references: [
      "McKaskill, T. (2010) *Ultimate Exits: The Secret Behind Selling Entrepreneurial Ventures at Staggering Prices*. Melbourne: Breakthrough Publications. [Accessible full text](https://tommckaskill.com/books/McKaskill-Ultimate-Exits%20copy.pdf).",
      "Pearson, R. (2011) *Month 10: From Technician to Entrepreneur*. Training manual. Small Business Academy, The Coaching Institute.",
    ],
  },
];
